#!/usr/bin/env bash
set -Eeuo pipefail

# Server B: interactive multi-inbound WireGuard egress and NAT gateway.
# One WireGuard interface/private key can connect to many inbound servers.
# Supported systems: Ubuntu and Debian.

umask 077

readonly STATE_DIR="/etc/xray-wireguard-exit"
readonly STATE_FILE="${STATE_DIR}/outbounds.env"
readonly PEER_DIR="${STATE_DIR}/outbounds-peers"
readonly REMOVED_PEER_DIR="${STATE_DIR}/removed-peers"

log() { printf '[outbounds] %s\n' "$*"; }
die() { printf '[outbounds] ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'EOF'
Usage:
  sudo ./outbounds.sh             Interactive menu
  sudo ./outbounds.sh init        Initialize/reconfigure the gateway
  sudo ./outbounds.sh add         Add an inbound entry
  sudo ./outbounds.sh update      Select and update an inbound entry
  sudo ./outbounds.sh remove      Interactively remove an inbound entry
  sudo ./outbounds.sh status      List entries and show WireGuard status

All inbound entries share this server's WireGuard public key. Each inbound
must have a unique tunnel IP inside WG_SUBNET.
EOF
}

require_root() {
  [[ ${EUID} -eq 0 ]] || die "run this script as root"
}

require_supported_os() {
  [[ -r /etc/os-release ]] || die "cannot identify the operating system"
  # shellcheck disable=SC1091
  source /etc/os-release
  case ${ID:-} in
    ubuntu|debian) ;;
    *) die "only Ubuntu and Debian are supported (detected: ${ID:-unknown})" ;;
  esac
  command -v apt-get >/dev/null 2>&1 || die "apt-get is required"
}

ask_text() {
  local prompt=$1 default=${2:-} answer=""
  if [[ -t 0 ]]; then
    if [[ -n $default ]]; then
      read -r -p "${prompt} [${default}]: " answer
    else
      read -r -p "${prompt}: " answer
    fi
  fi
  printf '%s' "${answer:-$default}"
}

ask_yes_no() {
  local prompt=$1 default=${2:-y} answer=""
  if [[ ! -t 0 ]]; then
    [[ $default == y ]]
    return
  fi
  if [[ $default == y ]]; then
    read -r -p "${prompt} [Y/n]: " answer
    answer=${answer:-y}
  else
    read -r -p "${prompt} [y/N]: " answer
    answer=${answer:-n}
  fi
  [[ ${answer,,} == y || ${answer,,} == yes ]]
}

select_existing_peer() {
  local choice i
  local files=()
  shopt -s nullglob
  files=("$PEER_DIR"/*.env)
  shopt -u nullglob
  ((${#files[@]} > 0)) || die "没有可更新的入口机"
  printf '\n已有入口机：\n'
  for ((i=0; i<${#files[@]}; i++)); do
    printf '%d) %s\n' "$((i + 1))" "$(basename "${files[$i]}" .env)"
  done
  read -r -p "请选择 [1-${#files[@]}]: " choice
  [[ $choice =~ ^[0-9]+$ ]] && ((choice >= 1 && choice <= ${#files[@]})) || die "选择无效"
  SELECTED_PEER_FILE=${files[$((choice - 1))]}
}

valid_wg_key() {
  [[ $1 =~ ^[A-Za-z0-9+/]{43}=$ ]]
}

valid_interface() {
  [[ $1 =~ ^[A-Za-z0-9_.-]{1,15}$ ]]
}

valid_peer_name() {
  [[ $1 =~ ^[A-Za-z0-9_-]{1,32}$ ]]
}

load_state() {
  [[ -r $STATE_FILE ]] || die "outbounds is not initialized; choose init first"
  # Root-owned mode-0600 file generated by this script.
  # shellcheck disable=SC1090
  source "$STATE_FILE"
  WG_INTERFACE=${WG_INTERFACE:-wg-exit}
  WG_ADDRESS=${WG_ADDRESS:-10.66.66.254/24}
  WG_SUBNET=${WG_SUBNET:-10.66.66.0/24}
}

write_state() {
  mkdir -p "$STATE_DIR"
  local temp_file
  temp_file=$(mktemp "${STATE_DIR}/outbounds.env.XXXXXX")
  {
    printf 'STATE_VERSION=%q\n' 2
    printf 'WG_INTERFACE=%q\n' "$WG_INTERFACE"
    printf 'WG_ADDRESS=%q\n' "$WG_ADDRESS"
    printf 'WG_SUBNET=%q\n' "$WG_SUBNET"
    printf 'WAN_INTERFACE=%q\n' "$WAN_INTERFACE"
  } >"$temp_file"
  chmod 600 "$temp_file"
  mv -f "$temp_file" "$STATE_FILE"
}

install_packages() {
  log "installing WireGuard and forwarding packages"
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wireguard-tools iproute2 iptables ca-certificates
}

detect_wan_interface() {
  local detected
  detected=$(ip -4 route show default | awk \
    '/default/ {for (i=1; i<=NF; i++) if ($i=="dev") {print $(i+1); exit}}')
  [[ -n $detected ]] || die "could not detect the IPv4 internet interface"
  printf '%s' "$detected"
}

protect_wireguard_config() {
  local config="/etc/wireguard/${WG_INTERFACE}.conf"
  [[ -r $STATE_FILE || ! -e $config ]] && return
  if [[ ${FORCE:-0} != 1 ]] && ! ask_yes_no \
    "${config} already exists. Back it up and replace it?" n; then
    die "kept the existing WireGuard configuration"
  fi
  local backup
  backup="${config}.bak-$(date +%Y%m%d%H%M%S)"
  cp -a "$config" "$backup"
  log "existing WireGuard config backed up to ${backup}"
}

ensure_private_key() {
  mkdir -p "$STATE_DIR"
  if [[ ! -s ${STATE_DIR}/outbounds-wg.key ]]; then
    wg genkey >"${STATE_DIR}/outbounds-wg.key"
    chmod 600 "${STATE_DIR}/outbounds-wg.key"
  fi
}

public_key() {
  wg pubkey <"${STATE_DIR}/outbounds-wg.key"
}

write_sysctl_config() {
  cat >/etc/sysctl.d/90-xray-wireguard-exit.conf <<'EOF'
net.ipv4.ip_forward = 1
EOF
  sysctl --system >/dev/null
}

load_peer_file() {
  local file=$1
  PEER_NAME=""
  PEER_ENDPOINT=""
  PEER_PUBLIC_KEY=""
  PEER_ALLOWED_IP=""
  # Root-owned mode-0600 file generated by this script.
  # shellcheck disable=SC1090
  source "$file"
}

write_peer_file() {
  local file=$1 temp_file
  mkdir -p "$PEER_DIR"
  temp_file=$(mktemp "${PEER_DIR}/peer.XXXXXX")
  {
    printf 'PEER_NAME=%q\n' "$PEER_NAME"
    printf 'PEER_ENDPOINT=%q\n' "$PEER_ENDPOINT"
    printf 'PEER_PUBLIC_KEY=%q\n' "$PEER_PUBLIC_KEY"
    printf 'PEER_ALLOWED_IP=%q\n' "$PEER_ALLOWED_IP"
  } >"$temp_file"
  chmod 600 "$temp_file"
  mv -f "$temp_file" "$file"
}

write_wireguard_config() {
  load_state
  ensure_private_key
  local private_key config temp_dir temp_file peer_file
  private_key=$(<"${STATE_DIR}/outbounds-wg.key")
  config="/etc/wireguard/${WG_INTERFACE}.conf"
  mkdir -p /etc/wireguard "$PEER_DIR"
  temp_dir=$(mktemp -d "/etc/wireguard/.${WG_INTERFACE}.XXXXXX")
  temp_file="${temp_dir}/${WG_INTERFACE}.conf"
  cat >"$temp_file" <<EOF
[Interface]
Address = ${WG_ADDRESS}
PrivateKey = ${private_key}
Table = off
PostUp = iptables -C FORWARD -i %i -o ${WAN_INTERFACE} -j ACCEPT 2>/dev/null || iptables -I FORWARD 1 -i %i -o ${WAN_INTERFACE} -j ACCEPT
PostUp = iptables -C FORWARD -i ${WAN_INTERFACE} -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || iptables -I FORWARD 1 -i ${WAN_INTERFACE} -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
PostUp = iptables -t nat -C POSTROUTING -s ${WG_SUBNET} -o ${WAN_INTERFACE} -j MASQUERADE 2>/dev/null || iptables -t nat -A POSTROUTING -s ${WG_SUBNET} -o ${WAN_INTERFACE} -j MASQUERADE
PostUp = sysctl -qw net.ipv4.conf.%i.rp_filter=0
PostDown = iptables -D FORWARD -i %i -o ${WAN_INTERFACE} -j ACCEPT 2>/dev/null || true
PostDown = iptables -D FORWARD -i ${WAN_INTERFACE} -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || true
PostDown = iptables -t nat -D POSTROUTING -s ${WG_SUBNET} -o ${WAN_INTERFACE} -j MASQUERADE 2>/dev/null || true
EOF

  shopt -s nullglob
  for peer_file in "$PEER_DIR"/*.env; do
    load_peer_file "$peer_file"
    cat >>"$temp_file" <<EOF

# ${PEER_NAME}
[Peer]
PublicKey = ${PEER_PUBLIC_KEY}
Endpoint = ${PEER_ENDPOINT}
AllowedIPs = ${PEER_ALLOWED_IP}
PersistentKeepalive = 25
EOF
  done
  shopt -u nullglob
  chmod 600 "$temp_file"
  if ! wg-quick strip "$temp_file" >/dev/null; then
    rm -f "$temp_file"
    rmdir "$temp_dir"
    die "generated multi-peer WireGuard configuration is invalid"
  fi
  mv -f "$temp_file" "$config"
  rmdir "$temp_dir"
}

restart_wireguard() {
  load_state
  systemctl daemon-reload
  systemctl enable "wg-quick@${WG_INTERFACE}.service" >/dev/null
  if systemctl is-active --quiet "wg-quick@${WG_INTERFACE}.service"; then
    systemctl restart "wg-quick@${WG_INTERFACE}.service"
  else
    systemctl start "wg-quick@${WG_INTERFACE}.service"
  fi
}

peer_conflicts() {
  local new_name=$1 new_key=$2 new_ip=$3 file
  shopt -s nullglob
  for file in "$PEER_DIR"/*.env; do
    load_peer_file "$file"
    [[ $PEER_NAME == "$new_name" ]] && continue
    [[ $PEER_PUBLIC_KEY != "$new_key" ]] || {
      shopt -u nullglob
      die "public key is already used by entry ${PEER_NAME}"
    }
    [[ $PEER_ALLOWED_IP != "$new_ip" ]] || {
      shopt -u nullglob
      die "tunnel IP is already used by entry ${PEER_NAME}"
    }
  done
  shopt -u nullglob
}

init_mode() {
  require_root
  require_supported_os
  local existing=0
  local previous_wg_interface=""
  if [[ -r $STATE_FILE ]]; then
    load_state
    previous_wg_interface=$WG_INTERFACE
    existing=1
    log "reconfiguring the existing outbounds gateway"
  else
    WG_INTERFACE=${WG_INTERFACE:-wg-exit}
    WG_ADDRESS=${WG_ADDRESS:-10.66.66.254/24}
    WG_SUBNET=${WG_SUBNET:-10.66.66.0/24}
    WAN_INTERFACE=${WAN_INTERFACE:-}
  fi

  WG_INTERFACE=$(ask_text "WireGuard 接口名称" "$WG_INTERFACE")
  valid_interface "$WG_INTERFACE" || die "invalid WireGuard interface name"
  WG_ADDRESS=$(ask_text "出口机隧道地址" "$WG_ADDRESS")
  [[ $WG_ADDRESS == */* ]] || die "WG_ADDRESS must include a prefix"
  WG_SUBNET=$(ask_text "所有入口共用的隧道网段" "$WG_SUBNET")
  [[ $WG_SUBNET == */* ]] || die "WG_SUBNET must include a prefix"
  WAN_INTERFACE=$(ask_text "出口机公网网卡" \
    "${WAN_INTERFACE:-$(detect_wan_interface)}")
  valid_interface "$WAN_INTERFACE" || die "invalid internet interface name"
  [[ $WAN_INTERFACE != "$WG_INTERFACE" ]] || die "internet and WireGuard interfaces must differ"
  ((existing)) || protect_wireguard_config

  install_packages
  ensure_private_key
  write_state
  write_sysctl_config
  write_wireguard_config
  if [[ -n $previous_wg_interface && $previous_wg_interface != "$WG_INTERFACE" ]]; then
    systemctl disable --now "wg-quick@${previous_wg_interface}.service" 2>/dev/null || true
  fi
  restart_wireguard

  cat <<EOF

Outbounds initialized.
Shared WireGuard public key: $(public_key)
Outbounds tunnel address   : ${WG_ADDRESS}
EOF
  if ask_yes_no "现在添加第一台入口机吗？" y; then
    add_mode
  fi
}

next_default_name() {
  local index=1
  while [[ -e ${PEER_DIR}/inbound${index}.env ]]; do
    ((index++))
  done
  printf 'inbound%s' "$index"
}

configure_peer_mode() {
  local file=$1
  local requested_endpoint requested_key requested_ip
  requested_endpoint=$(ask_text "入口机 WireGuard 地址（域名或IP:端口）" "$PEER_ENDPOINT")
  [[ $requested_endpoint == *:* ]] || die "endpoint must include a UDP port"
  requested_key=$(ask_text "入口机 WireGuard 公钥" "$PEER_PUBLIC_KEY")
  valid_wg_key "$requested_key" || die "invalid inbound WireGuard public key"
  requested_ip=$(ask_text "入口机唯一隧道 IP（/32）" "$PEER_ALLOWED_IP")
  [[ $requested_ip == */32 ]] || die "inbound tunnel IP must use /32"
  peer_conflicts "$PEER_NAME" "$requested_key" "$requested_ip"
  PEER_ENDPOINT=$requested_endpoint
  PEER_PUBLIC_KEY=$requested_key
  PEER_ALLOWED_IP=$requested_ip
  write_peer_file "$file"
  write_wireguard_config
  restart_wireguard

  cat <<EOF

Entry ${PEER_NAME} installed.
Outbounds shared public key: $(public_key)

Return to that inbound server, choose "Update WireGuard exit", select the
matching exit, and paste the public key above.
EOF
}

add_mode() {
  require_root
  require_supported_os
  load_state
  mkdir -p "$PEER_DIR"

  local default_name name file
  default_name=$(next_default_name)
  name=$(ask_text "新入口名称（字母、数字、下划线或连字符）" "$default_name")
  valid_peer_name "$name" || die "invalid entry name"
  file="${PEER_DIR}/${name}.env"
  [[ ! -e $file ]] || die "入口 ${name} 已存在，请使用‘更新入口机’"
  PEER_NAME=$name PEER_ENDPOINT="" PEER_PUBLIC_KEY="" PEER_ALLOWED_IP=""
  configure_peer_mode "$file"
}

update_mode() {
  require_root
  require_supported_os
  load_state
  select_existing_peer
  load_peer_file "$SELECTED_PEER_FILE"
  configure_peer_mode "$SELECTED_PEER_FILE"
}

list_entries() {
  local file count=0
  mkdir -p "$PEER_DIR"
  printf '\n%-18s %-24s %-18s\n' NAME ENDPOINT TUNNEL_IP
  printf '%-18s %-24s %-18s\n' '------------------' '------------------------' '------------------'
  shopt -s nullglob
  for file in "$PEER_DIR"/*.env; do
    load_peer_file "$file"
    printf '%-18s %-24s %-18s\n' "$PEER_NAME" "$PEER_ENDPOINT" "$PEER_ALLOWED_IP"
    ((count+=1))
  done
  shopt -u nullglob
  ((count > 0)) || printf '(no inbound entries)\n'
}

remove_mode() {
  require_root
  load_state
  list_entries
  local name file destination
  name=$(ask_text "要移除的入口名称" "")
  valid_peer_name "$name" || die "invalid entry name"
  file="${PEER_DIR}/${name}.env"
  [[ -r $file ]] || die "entry ${name} does not exist"
  ask_yes_no "确认移除入口 ${name}？" n || return
  mkdir -p "$REMOVED_PEER_DIR"
  destination="${REMOVED_PEER_DIR}/${name}-$(date +%Y%m%d%H%M%S).env"
  mv "$file" "$destination"
  write_wireguard_config
  restart_wireguard
  log "entry removed; recoverable copy saved at ${destination}"
}

status_mode() {
  require_root
  load_state
  list_entries
  printf '\nShared public key: %s\n' "$(public_key)"
  systemctl --no-pager --full status "wg-quick@${WG_INTERFACE}.service" || true
  printf '\n=== WireGuard peers ===\n'
  wg show "$WG_INTERFACE" || true
  printf '\n=== Forwarding/NAT ===\n'
  sysctl net.ipv4.ip_forward
  iptables -S FORWARD | grep -F "$WG_INTERFACE" || true
  iptables -t nat -S POSTROUTING | grep -F "$WAN_INTERFACE" || true
}

interactive_menu() {
  require_root
  [[ -t 0 ]] || die "interactive terminal required; use a subcommand"
  while true; do
    cat <<'EOF'

=== 出口机菜单 ===
1) 初始化或重新配置出口机
2) 添加入口机
3) 更新入口机
4) 移除入口机
5) 列出入口并查看状态
0) 退出
EOF
    read -r -p "请选择 [0-5]: " choice
    case $choice in
      1) init_mode ;;
      2) add_mode ;;
      3) update_mode ;;
      4) remove_mode ;;
      5) status_mode ;;
      0) return ;;
      *) printf '无效选项。\n' ;;
    esac
  done
}

case ${1:-menu} in
  menu) interactive_menu ;;
  init|install) init_mode ;;
  add) add_mode ;;
  update) update_mode ;;
  remove) remove_mode ;;
  status|list) status_mode ;;
  help|-h|--help) usage ;;
  *) usage >&2; exit 2 ;;
esac
